### PR TITLE
add basic support for code folding in editor and output

### PR DESCRIPTION
**Pull request by kylealwyn**

### CODE REVIEW

**Comment by kylealwyn** [comment]
yo @wellsjo I can't seem to reopen the pull request or create a new one through github gui... some quick searching looks like the repo owner (you) can comment on this pull request and a button will show saying "comment and re-open." not sure if it's for issues or pull requests as well. off on vacation tomorrow so won't online till monday.

**Comment by wellsjo** [comment]
@kylealwyn unfortunately that button is greyed out for me. I inadvertently I changed commit history when I changed the email in my git config, which means our histories are different now. You could still use [git-cherrypick](https://git-scm.com/docs/git-cherry-pick)

**Comment by kylealwyn** [comment]
@wellsjo rebasing did the trick. opened a new request: https://github.com/wellsjo/JSON-Splora/pull/27

**Comment by wellsjo** [comment]
Great! 😄

**Pull request closed without merging**
